# Generated by Django 4.1.2 on 2022-10-14 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
